baseURL: '/'
languageCode: 'en-us'
title: 'Scalereal'
defaultContentLanguage: en
languages:
    en:
        lang: en
        languageName: English
        weight: 1
MetaDataFormat: 'yaml'

theme: scalereal

googleAnalytics: 'UA-141833521-1'

params:
    navigation:
        - name: Home
          url: /
        - name: Services
          url: /services
        - name: Projects
          url: /projects
        - name: Blog
          url: /blogs
        - name: Company
          url: /company
        - name: Contact
          url: /contact
    fonts:
        google: [['Open Sans', '300,400,600,700,800']]
